service: employee-book-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  role: arn:aws:iam::122610498731:role/s3-fullaccess
  apiGateway:
    minimumCompressionSize: 1024
  logs:
    restApi: true
  environment: 
    DB_URL: ${env:DB_URL, ssm:/employee-book-env/DB_URL}
  
custom:
  dotenv:
    # Load .env only when running offline
    overwrite: true
    path: .env  

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    packages: external  

functions:
  api:
    handler: src/index.handler
    timeout: 29
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true