service: employee-book-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  role: arn:aws:iam::122610498731:role/s3-fullaccess
  environment:
    DB_URL: ${env:DB_URL}
    S3_BUCKET: ${env:S3_BUCKET}
    AWS_ACCESS_KEY: ${env:AWS_ACCESS_KEY}
    AWS_SECRET_KEY: ${env:AWS_SECRET_KEY}



plugins:
  - serverless-offline



build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    packages: external  

functions:
  api:
    handler: src/index.handler
    timeout: 30
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true